application:
  name: loan-fulfilment-service

tracer:
  host: ${TRACER_HOST:localhost}
  port: ${TRACER_PORT:6831}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:kafka:9092}
    producer:
      properties:
        interceptor:
          classes: io.opentracing.contrib.kafka.TracingProducerInterceptor

  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017/loan-fulfilment-service}

loan-fulfilment-service:
  mongo:
    database-name: loan-fulfilment-service
    collection-name: LoanApplication
  kafka:
    loan-application-event:
      topic: loanApplicationEvent
      producer:
        client-id: loanApplicationProducer
        properties:
          interceptor:
            classes: io.opentracing.contrib.kafka.TracingProducerInterceptor
      consumer:
        client-id: loanApplicationEventConsumer
        group-id: loanApplicationEvent-loanFulfilment-consumer-group
        auto-offset-reset: latest
        properties:
          interceptor:
            classes: io.opentracing.contrib.kafka.TracingConsumerInterceptor
    need-loan-event:
      topic: needLoanEvent
      consumer:
        client-id: needLoanEventConsumer
        group-id: needLoanEvent-loanFulfilment-consumer-group
        auto-offset-reset: latest
        properties:
          interceptor:
            classes: io.opentracing.contrib.kafka.TracingConsumerInterceptor
    loan-offer-event:
      topic: loanOfferDataAvailableForLoanProcessing
      consumer:
        client-id: loanOfferEventConsumer
        group-id: loanOfferEvent-loanFulfilment-consumer-group
        auto-offset-reset: latest
        properties:
          interceptor:
            classes: io.opentracing.contrib.kafka.TracingConsumerInterceptor
    screening-result-event:
      topic: screeningDataAvailableForLoanProcessing
      consumer:
        client-id: screeningEventConsumer
        group-id: screeningEvent-loanFulfilment-consumer-group
        auto-offset-reset: latest
        properties:
          interceptor:
            classes: io.opentracing.contrib.kafka.TracingConsumerInterceptor

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,info,health

server:
  port: 8085

